### ISSUE TITLE
error not returned when context time out occurs while updating ip pool CRD

### ISSUE THREAD

**Issue by rthakur-est** [k8snetworkplumbingwg/whereabouts#141]
The plugin doesn't return context timeout error when timeout happens while updating the ippools CRD.
This results in IP being allocated to container but the same IP is not reflected in the k8s datastore and finally causes duplicate IP allocation. 
This had happened when there were lots of stale entries in the ippools CRD and reasonable load on apiserver/etcd.

**Comment by martinkennelly** [comment]
I was just about to file this issue, are you talking about this line not returning the err object: https://github.com/k8snetworkplumbingwg/whereabouts/blob/3dacc67009e2b9021f712aafabb1bd10f510736d/pkg/storage/kubernetes/ipam.go#L436

**Comment by rthakur-est** [comment]
> I was just about to file this issue, are you talking about this line not returning the err object:
> 
> https://github.com/k8snetworkplumbingwg/whereabouts/blob/3dacc67009e2b9021f712aafabb1bd10f510736d/pkg/storage/kubernetes/ipam.go#L436

Yes.
