### ISSUE TITLE
Massive perf boost if we enable ReleaseOnCancel for LE

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/whereabouts#144]
During testing, I see a great perf boost if we enable [ReleaseOnCancel](https://pkg.go.dev/k8s.io/client-go/tools/leaderelection#LeaderElectionConfig) for LE.

I think, its a good idea to enable this feature. We only cancel LE context after we are finished operations on the data that the lease is protecting.

**Comment by martinkennelly** [comment]
3 node master + 30 workers.

Right now with current master:
Number of pods 1200: All created: 137m 

With ReleaseOnCancel enabled + PR #142:
Number of pods 1200: All created: 3m25s, All deleted: 7m56s
Number of pods 2400: All created: 17m49s, All deleted: 21m27s
Number of pods 3000: All created: 26m, All deleted: 31m


@rthakur-est can you replicate this?

**Comment by rthakur-est** [comment]
> 3 node master + 30 workers.
> 
> Right now with current master:
> Number of pods 1200: All created: 137m
> 
> With ReleaseOnCancel enabled + PR #142:
> Number of pods 1200: All created: 3m25s, All deleted: 7m56s
> Number of pods 2400: All created: 17m49s, All deleted: 21m27s
> Number of pods 3000: All created: 26m, All deleted: 31m
> 
> @rthakur-est can you replicate this? (you can use [this](https://github.com/maiqueb/whereabouts-stopwatch/blob/main/hack/lrp-test.sh))

I will ask my team to try this.

**Comment by martinkennelly** [comment]
See here: https://github.com/k8snetworkplumbingwg/whereabouts/pull/145
