### ISSUE TITLE
[Question/Request] What's the target date of next whereabouts release?

### ISSUE THREAD

**Issue by zhanggbj** [k8snetworkplumbingwg/whereabouts#160]
Hi

I noticed the last release `0.4.2` is published several months ago (Jul 08, 2021). And since that, there're lots of changes based on the commit log, so I'm wondering if there's any plan to publish a new release recently. Thanks!

I'm asking as I'm working on packaging whereabouts to make it a package for users to manage it easily on [TCE](https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages). This needs a specific release and I would like to use the latest instead of 0.4.2. 

CC @dougbtv

**Comment by dougbtv** [comment]
@zhanggbj -- thank you for bringing this up at the NPWG.

We've tagged a new release @ https://github.com/k8snetworkplumbingwg/whereabouts/releases/tag/v0.5

**Comment by zhanggbj** [comment]
Cool! Thanks @dougbtv for the quick action.
