### ISSUE TITLE
Duplicate IPs due to IP reconciler cleaning up reservation of a newly created pod

### ISSUE THREAD

**Issue by rthakur-est** [k8snetworkplumbingwg/whereabouts#207]
We are seeing that IP reconciler is cleaning up IP reservation of a newly created POD on a cluster with large number of pods. And later this freed IP gets allocated to different POD resulting in duplicate IPs for the PODs. 
This is the sequence of events that might have happened - 
1. ip-reconciler fetches list of pods 
2. while ip-reconciler is fetching pods, pod X gets created and reserves an IP in ip-pool
3. ip-reconciler fetches ip reservations and sees IP allocated to pod X
4. ip-reconciler cleans up reservation for pod X since it didn't find it in step (1)

**Comment by maiqueb** [comment]
Howdy @rthakur-est . 

Now that #208 was merged, can we close this issue ? (should have requested you to add a `Fixes: ` clause ... )
