### ISSUE TITLE
Dual Stack support

### ISSUE THREAD

**Issue by Ayush21298** [k8snetworkplumbingwg/whereabouts#212]
## Type

New feature or Enhancement of existing feature

## Description

Is there any plan for supporting Dual stack in near future ?
*As we all know that Kubernetes v1.20+ started supporting Dual stack and it is a stable feature now.*

Also, at present,  is there any method of assigning multiple IP addresses from different ranges ? *(I couldn't find one)*
If it exists, we can start developing Dual stack feature on top of it.

**Comment by Ayush21298** [comment]
Thank you for your response @maiqueb :)
Sure, that will be a good start. Thank you for inviting me to the bi-monthly call.
Can you please let me know the schedule of the same ?
I could only find the info. about bi-weekly call [here](https://github.com/k8snetworkplumbingwg/community#meetings).

**Comment by maiqueb** [comment]
> Thank you for your response @maiqueb :) Sure, that will be a good start. Thank you for inviting me to the bi-monthly call. Can you please let me know the schedule of the same ? I could only find the info. about bi-weekly call [here](https://github.com/k8snetworkplumbingwg/community#meetings).

Oh I just had my wording word and confused bi-monthly with bi-weekly. That's the one - once every 2 weeks.

**Comment by hhhybb** [comment]
Sounds cool, and hope to see the dual stack support soon.

**Comment by Ayush21298** [comment]
@dougbtv can you please assign this issue to me based on #250 ? :)
