### ISSUE TITLE
etcd deprecation

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/whereabouts#231]
Also in discussion: https://github.com/k8snetworkplumbingwg/whereabouts/discussions/228

Just looking to get any input on any community members that are still using the etcd support? Over the course of time, we've mentioned that we wouldn't be extending it, and some functionality doesn't apply to the etcd backend. 

While the extensible factor of having the multiple backends is a good idea, in practice it tends to be more work and we're not sure who's using it. Additionally, having to also manage an etcd deployment as well is often more complicated, when whereabouts tends to be more k8s focused rather than being orchestration engine agnostic, especially as it's often used in tandem with Multus CNI (which is also k8s specific).

**Comment by dougbtv** [comment]
Also related to #230

**Comment by maiqueb** [comment]
Plan is:
- tag a release from latest master, and create a release branch from it.
- get rid of etcd stuff on latest master.
- backport **fixes** (not features) to the etcd branch for 90 days.

Stay tuned to this issue to know when the clock starts ticking ...

**Comment by maiqueb** [comment]
OK, the clock started ticking: here's the [new branch](https://github.com/k8snetworkplumbingwg/whereabouts/commits/release/v0.5-etcd).
