### ISSUE TITLE
Arm tagged images are actually amd64?

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/whereabouts#254]
I got a report that the image from https://github.com/k8snetworkplumbingwg/whereabouts/pkgs/container/whereabouts (tried 0.5.3-arm64 and 0.5.2-arm64

Ran and wound up with:

```
standard_init_linux.go:228: exec user process caused: exec format error
```

And it appears to have run in an amd64 environment

**Comment by lHumanizado** [comment]
Same error here, i solved cloning the repository and building my own image using Dockerfile.arm64 file

**Comment by BlaineEXE** [comment]
This is still an issue today with the v0.6.1 release. Anyone working on fixing this?

**Comment by BlaineEXE** [comment]
The `docker buildx` command should work for the action workflow: https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee
