### ISSUE TITLE
[BUG] go vet fails with undeclared name error

### ISSUE THREAD

**Issue by Ayush21298** [k8snetworkplumbingwg/whereabouts#279]
**Describe the bug**

`go vet` throws following error when run in the root directory of source code.

```
whereabouts$ go vet ./...
# github.com/k8snetworkplumbingwg/whereabouts/pkg/controlloop
vet: pkg/controlloop/pod_controller_test.go:72:10: undeclared name: podSpec
```

**Expected behavior**

`go vet` should throw no error

**To Reproduce**
1. `git clone https://github.com/k8snetworkplumbingwg/whereabouts`
2. Run `go vet ./...`

**Environment**:
- _Skipping it as it is not a functional error_

**Additional info / context**
Add any other information / context about the problem here.

- go version go1.18 linux/amd64

**Comment by maiqueb** [comment]
You just have to pass the test tags via CLI - `go vet --tags=test ./...` , as our [CI is doing](https://github.com/k8snetworkplumbingwg/whereabouts/blob/de88984d7952111fedcda4ce583c459716ef60d8/hack/test-go.sh#L9).

**Comment by Ayush21298** [comment]
> You just have to pass the test tags via CLI - `go vet --tags=test ./...` , as our [CI is doing](https://github.com/k8snetworkplumbingwg/whereabouts/blob/de88984d7952111fedcda4ce583c459716ef60d8/hack/test-go.sh#L9).

But shouldn't all the test related files have `+build test` tag ? :thinking:

**Comment by maiqueb** [comment]
the tests ? Why would you put the tests in a binary ?

**Comment by Ayush21298** [comment]
Actually `pod_control_test.go` requires `podSpec` here
https://github.com/k8snetworkplumbingwg/whereabouts/blob/acddfd52abb3da37b4403cecaed53bd21ef6a0c3/pkg/controlloop/pod_controller_test.go#L72

This is defined in `entity_generator.go` here 
https://github.com/k8snetworkplumbingwg/whereabouts/blob/acddfd52abb3da37b4403cecaed53bd21ef6a0c3/pkg/controlloop/entity_generators.go#L53-L60

But `entity_generator.go` has build flags 
https://github.com/k8snetworkplumbingwg/whereabouts/blob/acddfd52abb3da37b4403cecaed53bd21ef6a0c3/pkg/controlloop/entity_generators.go#L1-L3

Because of this the issue happens.

 

> > You just have to pass the test tags via CLI - `go vet --tags=test ./...` , as our [CI is doing](https://github.com/k8snetworkplumbingwg/whereabouts/blob/de88984d7952111fedcda4ce583c459716ef60d8/hack/test-go.sh#L9).
> 
> But shouldn't all the test related files have `+build test` tag ? thinking

I suggested this because I think `pod_control_test.go` should not be included in the binary until and unless `test` tag is present.

@maiqueb What do you think ? ^^

**Comment by maiqueb** [comment]
I think I don't understand what you mean; `pod_control_test.go` - along with anything not reachable from the main entrypoint of either the pod controller or the CNI plugin - will not be present in the binary, hence, there is no need to tag it.

**Comment by Ayush21298** [comment]
Continuing from the call, yes I agree it will be better to remove the tags from the files which don't require tags :)

I was just concern that all the `go vet` with and without tag should pass independently (all the dependent files should either have tags or don't i.e. kind of independent sets ) :)
