### ISSUE TITLE
[BUG] Backport IPV6 validation fix(https://github.com/k8snetworkplumbingwg/whereabouts/pull/297) to release v0.5 and v0.6

### ISSUE THREAD

**Issue by adilGhaffarDev** [k8snetworkplumbingwg/whereabouts#299]
**Describe the bug**
v0.5 and v0.6 are missing the ipv6 validation fix(https://github.com/k8snetworkplumbingwg/whereabouts/pull/297)  and we have the fix only on the main branch.

Backport IPV6 validation fix to release v0.5 and create patch v0.5.5. There is a v0.5 branch so we can backport to it but we don't have v0.6 branch so I am not sure how should we go forward with that, should we just create a patch from main or instead of the patch just create a new release?

**Comment by maiqueb** [comment]
@dougbtv do we even have a policy about how far back we should backport fixes ?

**Comment by adilGhaffarDev** [comment]
Closing this issue because maintainers decided to create a new release tag instead of backporting. It was decided in the community meeting that backport will be only done on major releases.
