### ISSUE TITLE
[BUG] stuck in a leader election loop

### ISSUE THREAD

**Issue by caribbeantiger** [k8snetworkplumbingwg/whereabouts#303]
After reboot, a delete pod event causes  whereabouts to get stuck in a leader election loop, and pod never goes out of this state.

1. Reboot the worker node (might need to do it several times) 
2. delete pod 
3. pod stuck deleting since no response from whereabouts.
4. get whereabout logs and see error :   error retrieving resource lock /whereabouts: an empty namespace may not be set when a resource name is provided

**Environment**:
- Whereabouts version : v0.6
- Others:  AWS EKS 1.24

**Additional info / context**
Add any other information / context about the problem here.
[whereabouts logs.txt](https://github.com/k8snetworkplumbingwg/whereabouts/files/10866115/whereabouts.logs.txt)
[whereabouts pod describe.txt](https://github.com/k8snetworkplumbingwg/whereabouts/files/10866139/whereabouts.pod.describe.txt)

**Comment by caribbeantiger** [comment]
any luck looking into this?

**Comment by mlguerrero12** [comment]
@pukubee, please raise a new issue with logs attached
