### ISSUE TITLE
[BUG] could not create the pod networks controller

### ISSUE THREAD

**Issue by echel0n-TR** [k8snetworkplumbingwg/whereabouts#332]
**Describe the bug**
```
$ kubectl logs -n kube-system whereabouts-4qldx
Done configuring CNI.  Sleep=false
2023-05-19T04:32:47Z [debug] Filtering pods with filter key 'spec.nodeName' and filter value ''
2023-05-19T04:32:47Z [error] could not create the pod networks controller: Could not find node with node name ''.: resource name may not be empty
```

**Environment**:
- Whereabouts version : 0.6.1
- Kubernetes version (use `kubectl version`): v1.27.1

**Comment by Armstrong4444** [comment]
Same problem. I solved it by typing tag _v0.6.1-amd64_ explicitly in _daemonset-install.yaml_. Instead of tag _latest-amd64_

**Comment by sebrandon1** [comment]
Agreed we were able to move forward with the above as well.

**Comment by dougbtv** [comment]
Thanks for the report -- and the updates in the associated ticket, I've release https://github.com/k8snetworkplumbingwg/whereabouts/releases/tag/v0.6.2 which appears to have the fix for solving this issue.

**Comment by loekalive** [comment]
For me this exact issue is introduced when updating from v0.6.1 to v0.6.2, so that presumed fix might not be entirely complete.
